{
 "title": "API - SLOs",
 "refresh": "30s",
 "panels": [
  {
   "title": "Disponibilidade (24h)",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "1 - (sum(increase(http_requests_total{status=~\"5..\"}[24h])) / sum(increase(http_requests_total[24h])))"
    }
   ]
  },
  {
   "title": "Erro % (1h)",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{status=~\"5..\"}[1h])) / sum(rate(http_requests_total[1h]))) * 100"
    }
   ]
  },
  {
   "title": "Latência p95 (5m)",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))"
    }
   ]
  },
  {
   "title": "SLO por rota (p95 e erro %)",
   "type": "table",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 12 },
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.95, sum by (le, route) (rate(http_request_duration_seconds_bucket[5m]))), \"__name__\", \"p95\", \"__name__\", \".*\")"
    },
    {
     "expr": "label_replace(((sum by (route) (rate(http_requests_total{status=~\"5..\"}[5m]))) / (sum by (route) (rate(http_requests_total[5m])))) * 100, \"__name__\", \"error_percent\", \"__name__\", \".*\")"
    }
   ]
  }
 ]
}